### ISSUE TITLE
Issue 2: User can turn their car.

### ISSUE THREAD

**Issue by josh-tjiauw** [josh-tjiauw/driving-game#3]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Query the car image.
- [x] Add event listener to the document, listening for all 4 arrow keys.
- [x] Using JS, rotate the car image's css so that it faces the direction the arrow key is pressed.
