### ISSUE TITLE
Issue 3: User can start their car.

### ISSUE THREAD

**Issue by josh-tjiauw** [josh-tjiauw/driving-game#4]
Hints!
Add a location to your data model to hold the car's x and y coordinates on the page.
Use absolute positioning for your image.
Use the style property of element objects to change your car's top and left box offset styles.
Move your car every 16 milliseconds for a smooth movement.
The car doesn't have to change directions yet, that's a different feature.

## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add a location to your data model to hold the car's x and y coordinates on the page.
- [x] Use absolute positioning for your image.
- [x] Use setTimeOut method to move car every 16ms.
