### ISSUE TITLE
Issue 4: User can stop their car.

### ISSUE THREAD

**Issue by josh-tjiauw** [josh-tjiauw/driving-game#5]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Add a boolean in data model to indicate if the car is driving or not.
- [x] Add and statements in the event listener to check if the car is driving from data model.
- [x] Make the function to stop the car using clearInterval method.
