### ISSUE TITLE
Issue 5: User can steer their car.

### ISSUE THREAD

**Issue by josh-tjiauw** [josh-tjiauw/driving-game#6]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] Add conditionals for when user presses the arrow keys and the car is moving.
- [x] Add conditionals in the move function to check which direction to move.
- [x] Add resets in the move function so that the car resets the timer, and move to the correct direction.
- [x] Check & Fix Bugs
